# Generated by Django 5.0.2 on 2024-02-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipt_generator.receipts'),
        ),
    ]
