version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgressql
      POSTGRES_USER: sarmad
      POSTGRES_PASSWORD: 654123
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
